//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemmanagement
    {
        public int id { get; set; }
        public Nullable<int> catogeryid { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string price { get; set; }
        public string expiry { get; set; }
        public string quantity { get; set; }
    }
}
